
deployment:
  # Don't edit this, it's required by CD script
  image: "<<image_name>>"

# This value is updated by CD on the canary branch
canary: false

minAvailable: "50%"

deployments:
  api:
    cmd: /api
    name: api
    replicas: 2
    ports:
      - containerPort: 8000
        name: api
        protocol: TCP